### ISSUE TITLE
Teams 4.0.0 does not recover from failed database connection

### ISSUE THREAD

**Issue by pmeulen** [OpenConext/OpenConext-teams#4]
A loadbalancer issue caused a switch to the secondary mysql database. Teams failed after that. It appears teams keeps using a persitent DB connection that has failed. Stacktrace below:

```prd64 Aug 15, 2014 12:21:57 AM org.apache.catalina.core.StandardWrapperValve invoke
prd64 SEVERE: Servlet.service() for servlet coin-api threw exception
prd64 org.springframework.dao.RecoverableDataAccessException: PreparedStatementCallback; SQL [select token_id, token from oauth_access_token where token_id = ?]; Communications link failure
prd64 The last packet successfully received from the server was 2,340,206 milliseconds ago.  The last packet sent successfully to the server was 0 milliseconds ago.; nested exception is com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure
prd64 The last packet successfully received from the server was 2,340,206 milliseconds ago.  The last packet sent successfully to the server was 0 milliseconds ago.
prd64   at org.springframework.jdbc.support.SQLExceptionSubclassTranslator.doTranslate(SQLExceptionSubclassTranslator.java:98)
prd64   at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
prd64   at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)
prd64   at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:603)
prd64   at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:637)
prd64   at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:666)
prd64   at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:674)
prd64   at org.springframework.jdbc.core.JdbcTemplate.queryForObject(JdbcTemplate.java:734)
prd64   at org.springframework.security.oauth2.provider.token.JdbcTokenStore.readAccessToken(JdbcTokenStore.java:146)
prd64   at org.springframework.security.oauth2.provider.token.DefaultTokenServices.loadAuthentication(DefaultTokenServices.java:198)
prd64   at org.springframework.security.oauth2.provider.authentication.OAuth2AuthenticationManager.authenticate(OAuth2AuthenticationManager.java:70)
prd64   at org.springframework.security.oauth2.provider.authentication.OAuth2AuthenticationProcessingFilter.doFilter(OAuth2AuthenticationProcessingFilter.java:108)
prd64   at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
prd64   at org.springframework.security.oauth.provider.filter.OAuthProviderProcessingFilter.doFilter(OAuthProviderProcessingFilter.java:182)
prd64   at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
prd64   at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:113)
prd64   at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
prd64   at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:113)
prd64   at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
prd64   at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:54)
prd64   at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
prd64   at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:87)
prd64   at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
prd64   at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:192)
prd64   at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:160)
prd64   at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
prd64   at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:259)
prd64   at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
prd64   at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
prd64   at nl.surfnet.coin.shared.log.diagnostics.DiagnosticsLoggerFilter.doFilter(DiagnosticsLoggerFilter.java:77)
prd64   at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
prd64   at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
prd64   at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
prd64   at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
prd64   at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
prd64   at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
prd64   at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
prd64   at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:298)
prd64   at org.apache.jk.server.JkCoyoteHandler.invoke(JkCoyoteHandler.java:190)
prd64   at org.apache.jk.common.HandlerRequest.invoke(HandlerRequest.java:291)
prd64   at org.apache.jk.common.ChannelSocket.invoke(ChannelSocket.java:769)
prd64   at org.apache.jk.common.ChannelSocket.processConnection(ChannelSocket.java:698)
prd64   at org.apache.jk.common.ChannelSocket$SocketConnection.runIt(ChannelSocket.java:891)
prd64   at org.apache.tomcat.util.threads.ThreadPool$ControlRunnable.run(ThreadPool.java:690)
prd64   at java.lang.Thread.run(Thread.java:744)
prd64 Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure
prd64 The last packet successfully received from the server was 2,340,206 milliseconds ago.  The last packet sent successfully to the server was 0 milliseconds ago.
prd64   at sun.reflect.GeneratedConstructorAccessor438.newInstance(Unknown Source)
prd64   at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
prd64   at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
prd64   at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
prd64   at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:1116)
prd64   at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3589)
prd64   at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3478)
prd64   at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4019)
prd64   at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2490)
prd64   at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2651)
prd64   at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2683)
prd64   at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2144)
prd64   at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:2310)
prd64   at com.jolbox.bonecp.PreparedStatementHandle.executeQuery(PreparedStatementHandle.java:172)
prd64   at org.springframework.jdbc.core.JdbcTemplate$1.doInPreparedStatement(JdbcTemplate.java:644)
prd64   at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:587)
prd64   ... 41 more
prd64 Caused by: java.net.SocketException: Connection reset
prd64   at java.net.SocketInputStream.read(SocketInputStream.java:196)
prd64   at java.net.SocketInputStream.read(SocketInputStream.java:122)
prd64   at com.mysql.jdbc.util.ReadAheadInputStream.fill(ReadAheadInputStream.java:114)
prd64   at com.mysql.jdbc.util.ReadAheadInputStream.readFromUnderlyingStreamIfNecessary(ReadAheadInputStream.java:161)
prd64   at com.mysql.jdbc.util.ReadAheadInputStream.read(ReadAheadInputStream.java:189)
prd64   at com.mysql.jdbc.MysqlIO.readFully(MysqlIO.java:3036)
prd64   at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3489)
prd64   ... 51 more```

**Comment by lvonk** [comment]
This was actually in issue in OpenConext-api.

The commit SHA: OpenConext/OpenConext-api@134911ded17c6308de1f93b29d045fc4749454ca fixes this. It is waiting to be merged from the groupzy branch in api to the master.

**Comment by thijskh** [comment]
Since Teams no longer uses OpenConext-api, this can be closed.
